### ISSUE TITLE
Tare service to offset measurements

### ISSUE THREAD

**Issue by ipa-lth** [tork-a/dynpick_driver#29]
We need a functionality to tare the sensor just before actually using it in an robotic application. For many cases a single tare (offseting the current measurements to be zero and using this offset as a reference) is much easier and more robust than a full weight compensation (Having both worked best for us so far.)

I would suggest to implement this function (e.g. as a srv call) into the driver.

My question is if there is a build in command in the dynpick serial protokol. If so we should use this, if not it is fairly easy to implement it otherwise.

Please let me know your opinion. If there is interest I would gladly contribute to this driver.

**Comment by 130s** [comment]
Great to hear from you @ipa-lth!

> My question is if there is a build in command in the dynpick serial protokol. If so we should use this, if not it is fairly easy to implement it otherwise.

I'm not sure. Original developer of the ROS driver @534o may have insight. Also sounds like you have a device? Then you could consult the manufacturer [Wacoh Tech](http://www.wacoh-tech.com/en/). I personally prefer to relying on the proprietary software and avoid custom feature on ROS driver side as much as possible.

**Comment by 130s** [comment]
Great to hear from you @ipa-lth!

> My question is if there is a build in command in the dynpick serial protokol. If so we should use this, if not it is fairly easy to implement it otherwise.

I'm not sure. Original developer of the ROS driver @534o may have insight. Also sounds like you have a device? Then you could consult the manufacturer [Wacoh Tech](http://www.wacoh-tech.com/en/). I personally prefer relying on the proprietary software to making a custom feature on ROS driver side as much as possible.

**Comment by ipa-lth** [comment]
I totally agree on not implementing features which are already available on the device.
Yes, we have a dynpick, but we are lacking the manuals. I will try to contact Wacoh to get them.
My plan is to get something about this done this week.
Please let me know if you have any suggestions or comments.

**Comment by 534o** [comment]
maybe you have already send PR as #30 using "0" command and I also write the code to update the offset value at #31. Unfortunately I do not have sensor right know so did not checked on real hardware, 
On thing I'm afraid on #30 is that it stop sending force sensor values, which may have some side-effects on force-based control. But it this works for you, I think it's ok.

**Comment by ipa-lth** [comment]
You are right. #30 in fact stops sending force values for exactly 3 cycles.
However, doing a tare should not be done during active force control, because the offset should only be taken in a quasi static situation. I tested #30 on our hardware.

**Comment by 534o** [comment]
ok, merged #30

**Comment by ipa-frn** [comment]
Hi, I was frequently getting deadlocks when using the tare service and fixed it here: #42
